# Generated by Django 5.0.1 on 2024-01-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='cor_upload',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cor_upload',
        ),
    ]
