# Generated by Django 5.0.1 on 2024-01-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0002_remove_facultystaff_cor_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('comments', models.TextField()),
                ('certificate_of_registration', models.FileField(upload_to='cor/')),
                ('status', models.CharField(blank=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facultystaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WmsuClinicApp.facultystaff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WmsuClinicApp.student')),
            ],
        ),
    ]
