# Generated by Django 5.0.1 on 2024-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0011_admin_remove_profile_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_links',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_links',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_in_life',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('FacultyandStaff', 'Faculty and Staff')], max_length=20, null=True),
        ),
    ]
