# Generated by Django 5.0.1 on 2024-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0012_remove_profile_facebook_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ID_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
