# Generated by Django 5.0.1 on 2024-02-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0013_profile_id_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('purpose', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cor_upload', models.FileField(blank=True, null=True, upload_to='cor_uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('appointment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='WmsuClinicApp.appointment')),
                ('details_text', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
