# Generated by Django 5.0.1 on 2024-02-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0014_appointment_appointmentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
    ]
