# Generated by Django 5.0.1 on 2024-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0016_remove_appointmentdetails_details_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
