# Generated by Django 5.0.1 on 2024-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0017_alter_appointmentdetails_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
