# Generated by Django 5.0.1 on 2024-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0018_remove_appointmentdetails_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='current_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='current_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
