# Generated by Django 5.0.1 on 2024-01-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0006_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='facultystaff',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
    ]
