# Generated by Django 5.0.1 on 2024-01-31 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0007_remove_appointment_facultystaff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultystaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WmsuClinicApp.facultystaff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WmsuClinicApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WmsuClinicApp.patient'),
        ),
    ]
