# Generated by Django 5.0.1 on 2024-01-31 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmsuClinicApp', '0008_patient_appointmentdetails_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='facultystaff',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='student',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WmsuClinicApp.student'),
        ),
        migrations.DeleteModel(
            name='AppointmentDetails',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
